import type { PhraseCategory } from "./types";

// korean_food_phrases.html から構造化したフレーズ集
export const phraseCategories: PhraseCategory[] = [
  {
    id: "quantity",
    label: "量の調整",
    emoji: "🥢",
    desc: "いろいろ味見したい時の必須フレーズ。画面をそのまま店員に見せてもOK",
    phrases: [
      {
        big: true,
        korean: "반만 주세요. 가격은 그대로 괜찮아요.",
        reading: "パンマン ジュセヨ. カギョグン クデロ ケンチャナヨ.",
        meaning: "量を半分にしてください。値段はそのままで構いません。",
      },
      {
        big: true,
        korean: "다른 것도 먹고 싶어서요. 조금만 주세요.",
        reading: "タルン ゴット モッコ シポソヨ. チョグンマン ジュセヨ.",
        meaning: "他にも食べたいものがあるので。少しだけください。",
      },
      {
        situation: "追加の麺・ご飯を断る",
        korean: "면사리는 빼 주세요.",
        reading: "ミョンサリヌン ッペ ジュセヨ",
        meaning: "追加麺は抜いてください（광천식당で有効）",
      },
      {
        situation: "ご飯を少なめに",
        korean: "밥은 적게 주세요.",
        reading: "パブン チョッケ ジュセヨ",
        meaning: "ご飯は少なめにしてください",
      },
      {
        situation: "おかず（반찬）の追加を断る",
        korean: "반찬은 괜찮아요.",
        reading: "パンチャヌン ケンチャナヨ",
        meaning: "おかずは大丈夫です（要りません）",
      },
      {
        situation: "締めの追加を様子見",
        korean: "사리 추가는 나중에 할게요.",
        reading: "サリ チュガヌン ナジュンエ ハルケヨ",
        meaning: "追加（麺/ご飯）は後で決めます（ナッコプセで有効）",
      },
      {
        situation: "持ち帰りたい",
        korean: "포장해 주세요.",
        reading: "ポジャンヘ ジュセヨ",
        meaning: "包んでください（テイクアウト）。食べきれない時にも",
      },
    ],
  },
  {
    id: "order",
    label: "注文",
    emoji: "📋",
    desc: "入店から注文までの基本フロー",
    phrases: [
      { situation: "入店・人数を伝える", korean: "두 명이에요.", reading: "トゥ ミョンイエヨ", meaning: "2人です" },
      { situation: "注文したい", korean: "주문할게요.", reading: "チュムナルケヨ", meaning: "注文します" },
      { situation: "メニューを指差して", korean: "이거 하나 주세요.", reading: "イゴ ハナ ジュセヨ", meaning: "これ1つください" },
      { situation: "これを2つ", korean: "이거 두 개 주세요.", reading: "イゴ トゥゲ ジュセヨ", meaning: "これ2つください" },
      { situation: "おすすめを聞く", korean: "뭐가 맛있어요?", reading: "ムォガ マシッソヨ?", meaning: "何がおいしいですか?" },
      { situation: "2人でシェアしたい", korean: "둘이서 나눠 먹을게요.", reading: "トゥリソ ナンォ モグルケヨ", meaning: "2人で分けて食べます" },
      { situation: "水がほしい", korean: "물 주세요.", reading: "ムル ジュセヨ", meaning: "お水ください（韓国は基本セルフ。冷水機を探す）" },
      { situation: "店員を呼ぶ", korean: "저기요!", reading: "チョギヨ!", meaning: "すみません!（呼びかけ）" },
    ],
  },
  {
    id: "payment",
    label: "会計",
    emoji: "💳",
    desc: "T-money・Mastercard・現金の三本柱で対応",
    phrases: [
      { situation: "会計したい", korean: "계산할게요.", reading: "ケサナルケヨ", meaning: "お会計します" },
      { situation: "カードで払いたい", korean: "카드로 할게요.", reading: "カドゥロ ハルケヨ", meaning: "カードでお願いします" },
      { situation: "カード使えますか?", korean: "카드 돼요?", reading: "カドゥ トェヨ?", meaning: "カード使えますか?（ダメなら現金で）" },
      { situation: "現金で払う", korean: "현금으로 할게요.", reading: "ヒョングムロ ハルケヨ", meaning: "現金でお願いします" },
      {
        situation: "DCC（通貨選択）を回避",
        korean: "원화로 결제해 주세요.",
        reading: "ウォナロ キョルチェヘ ジュセヨ",
        meaning: "ウォンで決済してください（JPY選択は損、必ずKRW）",
        note: "カード端末で「日本円 or 韓国ウォン」と聞かれたら必ず韓国ウォン。日本円を選ぶとDCC手数料で3-5%損します。",
        tags: [{ label: "重要", color: "orange" }],
      },
      {
        situation: "複合決済（端数処理）",
        korean: "나눠서 결제할게요.",
        reading: "ナンォソ キョルチェハルケヨ",
        meaning: "分けて決済します（現金+カード等の複合払い）",
      },
      {
        situation: "現金を下ろしてきます",
        korean: "현금 뽑고 올게요.",
        reading: "ヒョングム ッポッコ オルケヨ",
        meaning: "現金下ろしてきます（万一現金不足の時）",
        note: "慌てず伝えればOK。韓国のローカル食堂ではよくあること。",
      },
    ],
  },
  {
    id: "trouble",
    label: "トラブル",
    emoji: "🆘",
    desc: "辛さ調整、アレルギー、席の問題など",
    phrases: [
      { situation: "辛さを控えめに", korean: "덜 맵게 해 주세요.", reading: "トル メプケ ヘ ジュセヨ", meaning: "辛さ控えめにしてください" },
      { situation: "辛い!水!!", korean: "너무 매워요! 물 주세요!", reading: "ノム メウォヨ! ムル ジュセヨ!", meaning: "辛すぎます! お水ください!" },
      { situation: "トイレはどこですか", korean: "화장실 어디에요?", reading: "ファジャンシル オディエヨ?", meaning: "トイレはどこですか?（韓国はビル共用のことが多い）" },
      { situation: "待ち時間を聞く", korean: "얼마나 기다려야 돼요?", reading: "オルマナ キダリョヤ トェヨ?", meaning: "どのくらい待ちますか?" },
      { situation: "順番待ちの登録", korean: "대기 등록하고 싶어요.", reading: "テギ トゥンノッカゴ シポヨ", meaning: "順番待ちの登録をしたいです（QR or 店頭）" },
      { situation: "感謝・美味しかったです", korean: "잘 먹었습니다!", reading: "チャル モゴッスムニダ!", meaning: "ごちそうさまでした!（退店時に言うと喜ばれる）" },
      { situation: "少々お待ちを", korean: "잠깐만요.", reading: "チャムカンマンヨ", meaning: "ちょっと待ってください（万能フレーズ）" },
    ],
  },
  {
    id: "basic",
    label: "基本",
    emoji: "💬",
    desc: "食事以外にも使える万能フレーズ",
    phrases: [
      { korean: "감사합니다.", reading: "カムサハムニダ", meaning: "ありがとうございます" },
      { korean: "괜찮아요.", reading: "ケンチャナヨ", meaning: "大丈夫です（断る時にも使える万能語）" },
      { korean: "네. / 아니요.", reading: "ネ / アニヨ", meaning: "はい / いいえ" },
      { korean: "한국어 못해요. 일본 사람이에요.", reading: "ハングゴ モッテヨ. イルボン サラミエヨ", meaning: "韓国語できません。日本人です" },
      { korean: "영어 메뉴 있어요?", reading: "ヨンオ メニュ イッソヨ?", meaning: "英語メニューありますか?" },
      { korean: "사진 찍어도 돼요?", reading: "サジン ッチゴド トェヨ?", meaning: "写真撮ってもいいですか?" },
      {
        situation: "数の言い方（注文に使う固有数詞）",
        korean: "하나 / 둘 / 셋 / 넷 / 다섯",
        reading: "ハナ / トゥル / セッ / ネッ / タソッ",
        meaning: "1 / 2 / 3 / 4 / 5（注文時は「하나 주세요」「두 개 주세요」）",
      },
    ],
  },
];
